# Generated by Django 5.0.7 on 2024-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='users', to='Users.account'),
        ),
    ]
