# Generated by Django 5.0.7 on 2024-07-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedtree',
            name='account',
        ),
    ]
