# Generated by Django 5.0.7 on 2024-07-29 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0003_remove_plantedtree_account'),
        ('Users', '0002_alter_customuser_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planted_trees', to='Users.account'),
        ),
    ]
